"""
The per-target adapter, as code:  Ascend -> bridge -> adapter -> target.

The built-in adapters cover common request patterns, but every real app can need its own — so an
adapter may be a Python module (generated by `adapter build --code`, or hand-written) that the
bridge runs exactly like a built-in one. These tests pin that contract and the generator.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "runtime"))

from adapters.custom_module import CustomModuleAdapter, _load_callable, CustomAdapterError  # noqa: E402
from discovery import codegen  # noqa: E402
from dispatch import ADAPTER_REGISTRY  # noqa: E402


def _run(adapter, prompt, config):
    return asyncio.new_event_loop().run_until_complete(adapter.send_prompt(prompt, config))


class TestRegistered:
    def test_custom_is_in_the_registry(self):
        assert ADAPTER_REGISTRY.get("custom") is CustomModuleAdapter

    def test_the_builtins_are_still_there(self):
        for name in ("direct_api", "sse_stream", "sentinel_stream", "browser", "bedrock"):
            assert name in ADAPTER_REGISTRY


class TestRunsAModule:
    def _write(self, tmp_path, body):
        m = tmp_path / "adp.py"
        m.write_text(body)
        return m

    def test_it_runs_send_prompt(self, tmp_path):
        m = self._write(tmp_path, "def send_prompt(prompt):\n    return 'echo: ' + prompt\n")
        r = _run(CustomModuleAdapter(), "hi", {"adapter_module": str(m)})
        assert r["success"] and r["response"] == "echo: hi"

    def test_it_accepts_handle_prompt_too(self, tmp_path):
        """A legacy shim named its function handle_prompt — drop it in unchanged."""
        m = self._write(tmp_path, "def handle_prompt(p):\n    return p.upper()\n")
        r = _run(CustomModuleAdapter(), "hi", {"adapter_module": str(m)})
        assert r["success"] and r["response"] == "HI"

    def test_a_module_that_raises_is_reported_not_swallowed(self, tmp_path):
        m = self._write(tmp_path, "def send_prompt(p):\n    raise RuntimeError('boom')\n")
        r = _run(CustomModuleAdapter(), "hi", {"adapter_module": str(m)})
        assert not r["success"] and "boom" in r["error"]

    def test_empty_reply_is_a_failure_not_a_false_pass(self, tmp_path):
        """A blank reply must not read as a successful turn — that's the false-pass shape."""
        m = self._write(tmp_path, "def send_prompt(p):\n    return ''\n")
        r = _run(CustomModuleAdapter(), "hi", {"adapter_module": str(m)})
        assert not r["success"]

    def test_a_missing_module_fails_loudly(self, tmp_path):
        r = _run(CustomModuleAdapter(), "hi", {"adapter_module": str(tmp_path / "nope.py")})
        assert not r["success"] and "not found" in r["error"]

    def test_a_module_without_the_function_is_rejected(self, tmp_path):
        m = self._write(tmp_path, "X = 1\n")
        with pytest.raises(CustomAdapterError):
            _load_callable(m)

    def test_a_syntax_error_is_named(self, tmp_path):
        m = self._write(tmp_path, "def send_prompt(p)\n return p\n")  # missing colon
        with pytest.raises(CustomAdapterError):
            _load_callable(m)


class TestGenerator:
    def _valid_module(self, src, tmp_path):
        m = tmp_path / "g.py"
        m.write_text(src)
        fn = _load_callable(m)   # must import and expose send_prompt
        return fn

    def test_direct_api_module_is_valid_python_with_send_prompt(self, tmp_path):
        cfg = {"adapter": "direct_api", "endpoint": "https://h/chat", "method": "POST",
               "body": {"message": "{{PROMPT}}"}, "response_path": "reply", "timeout_ms": 20000}
        src = codegen.generate_adapter_module("g", cfg, source="api")
        self._valid_module(src, tmp_path)
        assert "def send_prompt" in src and "https://h/chat" in src

    def test_nested_response_path_is_carried(self, tmp_path):
        cfg = {"adapter": "direct_api", "endpoint": "https://h/chat",
               "body": {"q": "{{PROMPT}}"}, "response_path": "status.data.answer"}
        src = codegen.generate_adapter_module("g", cfg, source="api")
        assert '"status"' in src and '"answer"' in src

    def test_sentinel_module_is_valid_and_has_markers(self, tmp_path):
        cfg = {"adapter": "sentinel_stream", "url": "https://h/chat",
               "begin_marker": "B_BEGIN", "end_marker": "B_END",
               "message": {"body": {"q": "{{PROMPT}}"}},
               "extract": {"events_path": "state.events", "text_field": "text",
                           "message_path": "message"}}
        src = codegen.generate_adapter_module("g", cfg, source="har")
        self._valid_module(src, tmp_path)
        assert "B_BEGIN" in src and "state" in src

    def test_unknown_shape_yields_a_scaffold_that_is_still_valid_python(self, tmp_path):
        cfg = {"adapter": "websocket_direct", "url": "wss://h/chat"}
        src = codegen.generate_adapter_module("g", cfg, source="har")
        assert "NotImplementedError" in src            # honest: not finished
        m = tmp_path / "s.py"; m.write_text(src)
        _load_callable(m)                               # but it imports cleanly

    def test_generated_direct_api_actually_substitutes_the_prompt(self, tmp_path):
        cfg = {"adapter": "direct_api", "endpoint": "https://h/chat",
               "body": {"outer": {"message": "{{PROMPT}}"}}, "response_path": "r"}
        src = codegen.generate_adapter_module("g", cfg, source="api")
        m = tmp_path / "g.py"; m.write_text(src)
        import importlib.util
        spec = importlib.util.spec_from_file_location("g", m)
        mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
        body = mod._body("hello \"world\"")
        assert body["outer"]["message"] == 'hello "world"'   # nested + quotes survive
