"""
codegen.py — turn a discovered contract into a per-app ADAPTER, as code.

Ascend -> bridge -> adapter -> target.  Every target gets its own adapter. For the common request patterns
we generate a small, self-contained Python module (stdlib + requests) that a person can read and
edit; for a target that fits none of them we still emit that module as a scaffold with the real
captured request in it, so a human (or a coding agent) finishes `send_prompt`.

The generated module implements one function:

    def send_prompt(prompt: str) -> str

which is exactly what runtime/adapters/custom_module.py runs. So a bespoke adapter and a built-in
one reach the bridge through the same path. Nothing generated is trusted until it answers the live
target (the hard gate in discovery/validate.py).
"""
from __future__ import annotations

import json
from typing import Any, Dict, Optional

PROMPT_TOKEN = "{{PROMPT}}"


def _py(obj: Any) -> str:
    """A Python literal for a JSON-ish value, stably formatted for a readable module."""
    return json.dumps(obj, indent=4, ensure_ascii=False)


def _body_fn(body: Any) -> str:
    """Render a _body(prompt) that rebuilds the request body with the prompt substituted.

    The captured body carries the {{PROMPT}} token where the prompt goes. We emit the body as a
    literal and replace the token at call time, so the operator sees the exact shape the app wants.
    """
    if isinstance(body, str):
        lit = _py(body)
        return (f"def _body(prompt):\n"
                f"    return {lit}.replace({_py(PROMPT_TOKEN)}, prompt)\n")
    # dict/other: JSON-encode, token-replace in the encoded string, decode back — this substitutes
    # the prompt no matter how deeply nested the field is, without walking the structure.
    lit = _py(body if body is not None else {"message": PROMPT_TOKEN})
    return (f"_BODY_TEMPLATE = {lit}\n\n\n"
            f"def _body(prompt):\n"
            f"    raw = json.dumps(_BODY_TEMPLATE)\n"
            f"    raw = raw.replace({_py(PROMPT_TOKEN)}, json.dumps(prompt)[1:-1])\n"
            f"    return json.loads(raw)\n")


def _extract_fn_direct(response_path: Optional[str]) -> str:
    if not response_path:
        return ("def _extract(data, raw_text):\n"
                "    # no response_path was pinned: fall back to the whole body\n"
                "    if isinstance(data, str):\n"
                "        return data\n"
                "    return raw_text\n")
    parts = response_path.split(".")
    return (f"_RESPONSE_PATH = {_py(parts)}\n\n\n"
            "def _extract(data, raw_text):\n"
            "    cur = data\n"
            "    for key in _RESPONSE_PATH:\n"
            "        if isinstance(cur, list):\n"
            "            try:\n"
            "                cur = cur[int(key)]\n"
            "            except (ValueError, IndexError):\n"
            "                return raw_text\n"
            "        elif isinstance(cur, dict) and key in cur:\n"
            "            cur = cur[key]\n"
            "        else:\n"
            "            return raw_text\n"
            "    return cur if isinstance(cur, str) else json.dumps(cur)\n")


def _header_block(headers: Dict[str, str]) -> str:
    return f"HEADERS = {_py(headers or {})}\n"


def _preamble(name: str, source: str, url: str, adapter_kind: str) -> str:
    return (
        f'"""Adapter for {name} — generated by `ascend adapter build` (from {source}).\n\n'
        f"Ascend -> bridge -> adapter (this file) -> your target.\n"
        f"This is the app's OWN adapter. Edit send_prompt() to handle anything the app needs;\n"
        f"re-prove it any time with:  ascend adapter validate --config {name}\n"
        f'"""\n'
        f"import json\n"
        f"import requests\n\n\n"
        f"META = {{\n"
        f"    \"target\": {_py(url)},\n"
        f"    \"kind\": {_py(adapter_kind)},\n"
        f"    \"generated_from\": {_py(source)},\n"
        f"}}\n\n\n"
    )


def _direct_api_module(name, source, cfg) -> str:
    url = cfg.get("endpoint") or cfg.get("url") or ""
    method = cfg.get("method", "POST")
    body = cfg.get("body")
    if body is None and isinstance(cfg.get("message"), dict):
        body = cfg["message"].get("body")
    return (
        _preamble(name, source, url, "direct_api")
        + f"URL = {_py(url)}\n"
        + f"METHOD = {_py(method)}\n"
        + _header_block(cfg.get("headers") or {})
        + f"TIMEOUT = {int(cfg.get('timeout_ms', 30000)) // 1000}\n\n\n"
        + _body_fn(body)
        + "\n\n"
        + _extract_fn_direct(cfg.get("response_path"))
        + "\n\n"
        "def send_prompt(prompt: str) -> str:\n"
        "    r = requests.request(METHOD, URL, headers=HEADERS, json=_body(prompt), timeout=TIMEOUT)\n"
        "    r.raise_for_status()\n"
        "    try:\n"
        "        data = r.json()\n"
        "    except ValueError:\n"
        "        return r.text\n"
        "    return _extract(data, r.text)\n"
    )


def _sentinel_module(name, source, cfg) -> str:
    url = cfg.get("url") or cfg.get("endpoint") or ""
    method = cfg.get("method", "POST")
    body = cfg.get("message", {}).get("body") if isinstance(cfg.get("message"), dict) else cfg.get("body")
    extract = cfg.get("extract") or {}
    events_path = (extract.get("events_path") or "").split(".") if extract.get("events_path") else []
    return (
        _preamble(name, source, url, "sentinel_stream")
        + f"URL = {_py(url)}\n"
        + f"METHOD = {_py(method)}\n"
        + _header_block(cfg.get("headers") or {})
        + f"TIMEOUT = {int(cfg.get('timeout_ms', 30000)) // 1000}\n"
        + f"BEGIN = {_py(cfg.get('begin_marker'))}\n"
        + f"END = {_py(cfg.get('end_marker'))}\n"
        + f"EVENTS_PATH = {_py(events_path)}\n"
        + f"TEXT_FIELD = {_py(extract.get('text_field', 'text'))}\n"
        + f"MESSAGE_PATH = {_py(extract.get('message_path') or '')}\n\n\n"
        + _body_fn(body)
        + "\n\n"
        "def _frames(raw):\n"
        "    import re\n"
        "    for m in re.findall(re.escape(BEGIN) + r'(.*?)' + re.escape(END), raw, re.S):\n"
        "        try:\n"
        "            yield json.loads(m.strip())\n"
        "        except ValueError:\n"
        "            continue\n\n\n"
        "def _text_from(obj):\n"
        "    cur = obj\n"
        "    for key in EVENTS_PATH:\n"
        "        if isinstance(cur, dict) and key in cur:\n"
        "            cur = cur[key]\n"
        "        else:\n"
        "            return None\n"
        "    events = cur if isinstance(cur, list) else [cur]\n"
        "    out = []\n"
        "    for ev in events:\n"
        "        node = ev.get(MESSAGE_PATH, ev) if (MESSAGE_PATH and isinstance(ev, dict)) else ev\n"
        "        if isinstance(node, dict) and isinstance(node.get(TEXT_FIELD), str):\n"
        "            out.append(node[TEXT_FIELD])\n"
        "    return ' '.join(out) if out else None\n\n\n"
        "def send_prompt(prompt: str) -> str:\n"
        "    r = requests.request(METHOD, URL, headers=HEADERS, json=_body(prompt), timeout=TIMEOUT)\n"
        "    r.raise_for_status()\n"
        "    parts = [t for t in (_text_from(f) for f in _frames(r.text)) if t]\n"
        "    return parts[-1] if parts else r.text\n"
    )


def _scaffold_module(name, source, cfg) -> str:
    """For a target that fits no known pattern: emit the real captured request + a clear TODO."""
    url = cfg.get("url") or cfg.get("endpoint") or ""
    return (
        _preamble(name, source, url, "custom")
        + f"URL = {_py(url)}\n"
        + f"METHOD = {_py(cfg.get('method', 'POST'))}\n"
        + _header_block(cfg.get("headers") or {})
        + f"TIMEOUT = {int(cfg.get('timeout_ms', 30000)) // 1000}\n\n\n"
        + _body_fn(cfg.get("body") or (cfg.get("message", {}) or {}).get("body"))
        + "\n\n"
        "def send_prompt(prompt: str) -> str:\n"
        "    # This target did not match a known pattern. The captured request is above.\n"
        "    # Finish this function: send `prompt`, return the app's reply as a string.\n"
        "    # `ascend adapter build --agent` can write this for you from the captured evidence.\n"
        "    r = requests.request(METHOD, URL, headers=HEADERS, json=_body(prompt), timeout=TIMEOUT)\n"
        "    r.raise_for_status()\n"
        "    raise NotImplementedError('finish send_prompt: extract the reply from r')\n"
    )


def generate_adapter_module(name: str, config: Dict[str, Any], source: str = "build") -> str:
    """Produce the source of a per-app adapter module from a discovered config.

    Chooses a generator by the discovered adapter kind; falls back to a scaffold that still carries
    the real request. The result is always a module exposing send_prompt(prompt) -> str.
    """
    kind = (config.get("adapter") or "").lower()
    if kind == "sentinel_stream":
        return _sentinel_module(name, source, config)
    if kind in ("direct_api", "", "api"):
        return _direct_api_module(name, source, config)
    # sse_stream and the platform adapters still have working built-in handlers; for those the
    # thin pointer config (adapter: <kind>) is correct and we do not force codegen. The scaffold
    # is only for genuinely unknown shapes.
    return _scaffold_module(name, source, config)


def browser_config_from_recipe(url: str, recipe: Dict[str, Any]) -> Dict[str, Any]:
    """A `browser` adapter config from what the capture actually did to the live widget.

    The capture already opened the widget, found the input, sent a prompt, and read the reply — so
    it knows the launcher, the chat frame, the input selector, how to send, and where the reply
    renders. This turns that into the adapter that DRIVES a real browser per probe, which is the
    only thing that works on a target whose HTTP endpoint refuses replay (anti-automation).
    """
    cfg: Dict[str, Any] = {
        "adapter": "browser",
        "_note": "driven through a real browser per probe (the HTTP endpoint refuses replay). "
                 "Generated by `adapter build --url`; tune selectors with `adapter show`.",
        "url": url,
        "headless": False,
        "pre_actions": [{"action": "dismiss_cookie", "description": "accept cookies if prompted"},
                        {"action": "wait", "ms": 2500}],
    }
    if recipe.get("launcher"):
        cfg["pre_actions"].append({"action": "click", "selector": recipe["launcher"],
                                   "timeout_ms": 20000, "description": "open the chat widget"})
        cfg["pre_actions"].append({"action": "wait", "ms": 4000})
    # the chat frame, matched by URL (robust for nested widgets)
    furl = recipe.get("input_frame_url") or ""
    if furl:
        needle = _frame_needle(furl, url)
        if needle:
            cfg["iframe"] = {"url_contains": needle}
    inp = recipe.get("input_selector") or "textarea, input[type='text']"
    cfg["wait_for_widget"] = {"selector": inp, "timeout_ms": 25000}
    cfg["input"] = {"selector": inp}
    send = recipe.get("send") or "enter"
    cfg["send"] = {"method": "enter"} if send == "enter" else {"method": "click", "selector": send}
    resp: Dict[str, Any] = {
        "wait_strategy": recipe.get("reply_strategy", "text_settle"),
        "container_selector": recipe.get("reply_container",
                                         "[class*='message'], [class*='bubble'], [class*='chat']"),
        "timeout_ms": 45000,
        "stabilization_delay_ms": 3000,
        "poll_interval_ms": 700,
    }
    cfg["response"] = resp
    return cfg


def _frame_needle(frame_url: str, page_url: str) -> str:
    """A distinctive path substring of the chat frame's URL, for iframe.url_contains.

    Prefer the frame's own path (e.g. '/chat/support'); avoid matching the host page itself.
    """
    from urllib.parse import urlsplit
    try:
        fp = urlsplit(frame_url)
        path = (fp.path or "").rstrip("/")
        if path and len(path) > 1:
            # last two path segments, distinctive enough to pick the chat frame out of many
            segs = [s for s in path.split("/") if s]
            return "/".join(segs[-2:]) if len(segs) >= 2 else segs[-1]
        # no path: fall back to the frame host if it differs from the page host
        if fp.netloc and fp.netloc not in page_url:
            return fp.netloc
    except Exception:
        pass
    return ""
