"""Generate docs/QA_COVERAGE.md: every command path, and how it was last proven to work."""
import re, glob, os, json, sys, datetime as dt
REPO = sys.argv[1]
SUB = os.path.expanduser("~/.claude/projects/-Users-phimmasonephonpaseuth-Projects/f7f167fe-1659-41b8-a3b8-1f9ee9638d6f/subagents")
txt = open(f"{REPO}/docs/COMMAND_MAP.md").read()
cmds = sorted(set(re.findall(r"`ascend ((?:[a-z][a-z-]*)(?: [a-z][a-z-]*)?)`", txt)))
used = {}
for f in glob.glob(f"{SUB}/agent-*.jsonl"):
    for line in open(f, encoding="utf-8", errors="replace"):
        for m in re.finditer(r"ascend\.py\s+([a-z][a-z-]*)(?:\s+([a-z][a-z-]*))?", line):
            k = m.group(1) + (" " + m.group(2) if m.group(2) else "")
            used[k] = used.get(k, 0) + 1
manual = json.load(open(sys.argv[2])) if len(sys.argv) > 2 else {}
rows = []
for c in cmds:
    n = used.get(c, 0)
    if c in manual: how = manual[c]
    elif n: how = f"live, by {n} agent invocation{'s' if n>1 else ''} in the 62-agent trial (2026-09-04/05)"
    else: how = "**not yet proven live** (unit tests only)"
    rows.append(f"| `ascend {c}` | {how} |")
today = dt.date.today().isoformat()
out = f"""# Command QA coverage — how each command was last proven

Generated by a script from `docs/COMMAND_MAP.md` and the transcripts of the agent trial; hand checks
are dated. "Live" means the command ran against the real demo tenant or a real target and did what
its documentation says. A command that is only unit-tested is marked as such -- offline tests are
regression guards, not proof.

Last regenerated: {today}. Command paths: {len(cmds)}.

| Command | Last proven by |
|---|---|
""" + "\n".join(rows) + "\n"
open(f"{REPO}/docs/QA_COVERAGE.md", "w").write(out)
unproven = [c for c in cmds if c not in manual and not used.get(c)]
print(f"{len(cmds)} commands; agent-proven {sum(1 for c in cmds if used.get(c))}; manual {len([c for c in cmds if c in manual])}; unproven: {unproven}")
