"""
custom_module.py — the per-app adapter, as code.

The paradigm is  Ascend -> bridge -> adapter -> target.  The bridge is generic; the ADAPTER is the part
that knows how to talk to one specific app, and every app gets its own. The built-in adapters cover
common request patterns, but real customer agents have bespoke complexity no fixed set can cover —
so an adapter may also BE a small Python module, written (or generated by `ascend adapter build`)
for exactly one app.

The contract is one function:

    def send_prompt(prompt: str) -> str:
        # Send one prompt to THIS app and return the reply. Anything goes in here:
        # signed requests, a multi-step auth handshake, streaming reassembly, an async
        # poll, driving a browser. Take as long as you need (set a big timeout_ms).

Optional module-level metadata for `adapter show`:

    META = {"target": "https://...", "kind": "custom", "generated_from": "har"}

This adapter loads that module and runs it, so the bridge treats a bespoke per-app adapter exactly
like a built-in one. The module is plain, inspectable code the operator reads before running
(`ascend adapter show`), it runs in a worker thread (a blocking turn cannot stall the event loop),
and — like every adapter — nothing is accepted until it answers the live target (the hard gate).
"""
from __future__ import annotations

import asyncio
import importlib.util
import time
from pathlib import Path
from typing import Any, Callable, Dict, Optional

from .base import BotAdapter


class CustomAdapterError(RuntimeError):
    pass


def _resolve_module_path(config: Dict[str, Any]) -> Path:
    """Where the app's adapter module lives.

    `adapter_module` is a filename resolved next to the config, or an absolute path. This mirrors
    how configs are resolved so the module travels with the engagement, beside its config.
    """
    ref = config.get("adapter_module") or config.get("module")
    if not ref:
        raise CustomAdapterError(
            "a custom adapter needs 'adapter_module' (the .py that implements send_prompt)")
    p = Path(str(ref)).expanduser()
    if p.is_absolute() and p.is_file():
        return p
    # resolve relative to the config dir (shared resolver, so CLI and bridge agree)
    try:
        from configs import config_dir
        cand = Path(config_dir()) / p.name
        if cand.is_file():
            return cand
    except Exception:
        pass
    if p.is_file():
        return p
    raise CustomAdapterError(f"adapter module not found: {ref}")


def _load_callable(path: Path) -> Callable[[str], str]:
    """Import the module and return its prompt handler.

    Accepts `send_prompt` (preferred) or `handle_prompt` (the shim name), so an operator can drop in
    an existing shim unchanged.
    """
    spec = importlib.util.spec_from_file_location(f"ascend_adapter_{path.stem}", str(path))
    if spec is None or spec.loader is None:
        raise CustomAdapterError(f"could not load adapter module: {path}")
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as exc:  # a syntax/import error in the generated code
        raise CustomAdapterError(f"{path.name} failed to import: {type(exc).__name__}: {exc}")
    fn = getattr(mod, "send_prompt", None) or getattr(mod, "handle_prompt", None)
    if not callable(fn):
        raise CustomAdapterError(
            f"{path.name} must define send_prompt(prompt) -> str (or handle_prompt)")
    return fn


def load_meta(config: Dict[str, Any]) -> Dict[str, Any]:
    """Read a module's META dict STATICALLY, without importing it.

    `adapter show` is the command an operator uses to inspect an adapter BEFORE trusting it, so it
    must not execute the module's code to do so. Parse the source and literal-eval the META
    assignment instead — no top-level code runs.
    """
    import ast
    try:
        path = _resolve_module_path(config)
        tree = ast.parse(path.read_text())
        for node in tree.body:
            if isinstance(node, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == "META" for t in node.targets):
                val = ast.literal_eval(node.value)
                return dict(val) if isinstance(val, dict) else {}
    except Exception:
        pass
    return {}


class CustomModuleAdapter(BotAdapter):
    """Run an app's own adapter module. One module per app; the bridge treats it like any adapter."""

    def __init__(self) -> None:
        self._fn: Optional[Callable[[str], str]] = None
        self._path: Optional[Path] = None

    def _ensure_loaded(self, config: Dict[str, Any]) -> Callable[[str], str]:
        path = _resolve_module_path(config)
        # reload if the module changed under us (an operator editing a generated adapter)
        if self._fn is None or self._path != path:
            self._fn = _load_callable(path)
            self._path = path
        return self._fn

    async def send_prompt(self, prompt: str, config: Dict[str, Any]) -> Dict[str, Any]:
        start = time.time()
        try:
            fn = self._ensure_loaded(config)
        except CustomAdapterError as exc:
            return self._fail(str(exc), start)

        try:
            if asyncio.iscoroutinefunction(fn):
                reply = await fn(prompt)
            else:
                # A per-app handler is usually blocking (requests, a poll loop). Run it off the
                # event loop so one slow turn cannot stall every other conversation.
                reply = await asyncio.get_running_loop().run_in_executor(None, fn, prompt)
        except Exception as exc:  # the app's own code raised
            return self._fail(f"adapter raised {type(exc).__name__}: {exc}", start,
                              module=str(self._path))

        if reply is None or (isinstance(reply, str) and not reply.strip()):
            return self._fail("adapter returned no text", start, module=str(self._path))
        return self._ok(str(reply), start, module=str(self._path),
                        adapter_module=self._path.name if self._path else None)
